### ISSUE TITLE
Refusing to install react-emoji-react as a dependency of itself

### ISSUE THREAD

**Issue by paejal** [conorhastings/react-emoji-react#11]
I can not solve this problem when i install `npm install react-emoji-react --save`

```
npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "react-emoji-react" "--save"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ENOSELF

npm ERR! Refusing to install react-emoji-react as a dependency of itself
```

please help me. thanks.

**Comment by conorhastings** [comment]
@Faezal13 in what project are you attempting to install it? If you are trying to install in a cloned version of this repo it won't work, but I haven't experienced trouble installing it into another package

**Comment by Faezal13** [comment]
hi @conorhastings  thanks for your information.
i want to install it to mattermost platform, did you colaboreate this emoji with mattermost?
