### ISSUE TITLE
The Demo site is broken. 

### ISSUE THREAD

**Issue by jshuadvd** [conorhastings/react-emoji-react#14]
It either re-routes me to your normal site or when it loads your demo, it is a blank page. Thanks!

**Comment by conorhastings** [comment]
thanks for the issue, should be fixed

**Comment by chinnuu05** [comment]
it's broken again, is this library still maintained?

anyway we can get esm module support?

**Comment by chinnuu05** [comment]
> thanks for the issue, should be fixed

it's broken again

I know this library is really old, but anyway we can get esm module support?
